### PR TITLE
Create GitHub action for lint, unit tests and integration test

### PR DESCRIPTION
**Pull request by mhdirkse**

### CODE REVIEW

**Comment by mhdirkse** [comment]
The tests have succeeded. Ready-for-review.

**Comment by mhdirkse** [comment]
Sorry, I was too quick to make this ready-for-review. The Cypress output is not yet stored with the artifacts.

**Comment by mhdirkse** [comment]
Caching works as intended now. Furthermore, the Cypress screenshots and videos and the Catalina log are stored as artifacts.

**Comment by celmoussaoui** [comment]
Do you think it might be useful to also run the Cypress tests on Firefox and Edge?

**Pull request merged**
